name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron : 30 02 * * * # 8 am IST Every day
    - cron : 00 14 * * * # 730 pm IST Every day
    - cron : 00 06 * * 1-5 # 1130 am IST Monday to Friday

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout the code
        uses: actions/checkout@v5.0.0

        - name: Install Node js























